### ISSUE TITLE
object not created properly when async in middleware

### ISSUE THREAD

**Issue by kelabang** [young-steveo/bottlejs#55] opened 2016-05-14 20:50 UTC
config not load properly
```
bottle.middleware('Config', (service, next) => {
	console.log('-- middleware config --')
	const target = __dirname + '/config'
	service
			.setupAsync(target)
			.then((data) => {
				console.log('-- config ready --', service.configuration)
				next()
			})
			.error((err) => {
				console.log('-- config not ready --')
				console.error(err)
			})
})
bottle.service('Server', Hapi.Server)
bottle.middleware('Server', (service, next) => {
	console.log('-- middleware server --')
	var config = bottle.container.Config
	console.log(config.configuration, '-- ++++++++')
	return service
})

```

config.configuration not loaded properly.
am i using this wrong way?

**Comment by young-steveo** [comment] 2016-05-17 14:19
@kelabang Thanks for reporting the issue.

This is an interesting problem, and not one to which I have a quick solution.  I can describe why it is not working, however:

The issue is with the fundamental way bottle instantiates and injects services.  This process is inherently synchronous, because property lookups are synchronous.  e.g.:

```js
bottle.service('Test', function Test() {});
let test = bottle.container.Test; // accessing the property calls the service constructor
```

As you can see above, the service is instantiated the moment the property is accessed on the container.  This is all achieved by the magic of JavaScript getters and setters  In the example, I would expect the `test` variable to be an instance of the `Test` constructor.

When resolving dependencies, bottle does essentially the same kind of property lookup.  Since getters are synchronous, we've basically come to an impasse.

---

With the above stated, it does seem to me that the `next` function in the middleware callback could imply that asynchronous operations would work, so I'm sorry for the confusion.

I'd be interested in brainstorming some async solutions to the problem.  In the meantime, checkout the discussion in https://github.com/young-steveo/bottlejs/issues/40 which is similar, yet not quite the same problem.

**Comment by young-steveo** [comment] 2016-05-19 15:02
I can't think of a good way to support this behavior in the library without introducing promises (which would make bottlejs too large) or introducing an alternative syntax.

For now, I think you should use a decorator to return the promise yourself:

```js
bottle.decorator('Config', config => {
    console.log('-- decorator config --');
    const target = __dirname + '/config';
    const setup = config.setupAsync(target);
    
    setup.error((err) => {
        console.log('-- config not ready --');
        console.error(err);
    });
    return setup;
});
bottle.service('Server', Hapi.Server);
bottle.decorator('Server', service => {
    console.log('-- decorator server --');
    bottle.container.Config.then(configuration => {
        console.log('-- config ready --', configuration);
    });
    return service;
});
```

Alternatively, call `setupAsync` only when you need it.

**Closed by young-steveo** 2016-05-19 15:02 UTC

**Comment by kelabang** [comment] 2016-05-19 21:19
Thx for your answer btw I am already fixed my logic code, now every async operation am doing it outside bottle , I am realize that `next()`  in middleware because in you're not using any callback or promise to catch value when I call `bottle.container.Config` it's just return it. I am just expecting `next()` method was there because operation was non-blocking.
